services:
  sync-db:
    container_name: idc-preship-sync-db
    ports: !override
      - "15449:5432"
  sync-server:
    container_name: idc-preship-sync-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@idc-preship-sync-db:5432/idc_sync
    ports: !override
      - "13161:3161"
